export default defineEventHandler(() => {
    return {
        "pvp": [
            "3X Gather/Pickup/Mining",
            "Furnace Splitter",
            "Quick Crafting and Recycle Time",
            "Fast Night time and Long Daytime",
            "Quick Ore Smelting with Autosplitter",
            "Sorting Button",
            "Quick Supply Drop Delivery",
            "Automatic TC and Trap Authorization",
            "Teleportation To Oust Post/Bandit Camp/Set Homes",
            "Trade",
            "Remove Tool",
            "Extra Bag",
            "Starter Kits",
            "VIP Kits"
        ],
        "pve": [
            "Recyclers are available on all monuments, including Dome, Ranch, and Large Barn.",
            "All monument CCTV Camera codes will be automatically added to the CCTV Station when it is placed",
            "The CCTV codes for the Cargo Ship will be broadcasted once the cargo ship spawns",
            "Supply drops will be delivered quickly, and parachuting down will be a bit fast. Please call it in your TC range zone",
            "NPC Vending Machines never go out of stock, and there are no pending transactions. In short, you can instantly buy things from all types of Vending machines",
            "Meat in the furnace, BBQ, or campfire will never overcook",
            "Teammates or clanmates will be automatically authorized on tool cupboards and codelocks. However, only the owner can remove code locks or items with locks, such as doors",
            "Teammates or clanmates will be automatically authorized on SAM sites and all types of traps. SAM sites will not target players until the Purge. This includes the owner, teammates, and clanmates, even if the purge is active",
            "Instant crafting of all item types is available (instant untying, researching, and mixing table is exclusive to Elite rank players)",
            "Ore smelting in all types of furnaces is 5X, excluding Electric Furnaces",
            "All players have Tier 0 (DLC items) and Electric Blueprints unlocked. They do not get wiped, so there's no need to worry",
            "7 Minute Night time and 45 Minutes Daytime with No Sun Glare",
            "Items will automatically split into slots in furnaces when the required fuel (wood) is present. Furnace Splitter",
            "Minicopters are equipped with two small storage boxes, each having more rows than a large storage box",
            "We have leaderboards for players to check playtime, resources gathered, PvP kills, etc",
            "We have timed ranks which are assigned to you for playing on our server, not how much you have played in rust. You can check your playtime and time left until next rank assigment using the commands below",
            "Our server operates on an RP system. You can earn RP by engaging in activities such as killing animals / Bradley APC, Helicopter, destroying barrels, and looting boxes. You can spend this RP in server shop",
            "We have raidable bases, where a base spawns with lots of loot. If you attack it first, it will be locked to you, ensuring that you are the only one who can loot it",
            "Open the server shop to sell items for RP, such as stones, and buy events like the Attack Helicopter or Buried Maps. You can use RP to purchase commands and items",
            "The Large Excavator is set to 5X. If you start the Large Excavator, it will be locked to you, ensuring that no one else can loot it except you, your teammates, and clanmates. Once it stops, you will have 15 minutes to loot it before it goes public. There is also a 10 Diesel limit",
            "You will come across many Purple Cards or Super Cards. These cards can function as all three types (Green, Red, Blue). However, each card has only 2 uses. You can sell any extra cards (green, blue, red) only in the server shop (/s)",
            "The player, team, or clan dealing the most damage to an item such as an animal, NPC, or attack helicopter will be entitled to loot it. Damage information will be displayed in the chat",
            "Building twigs, setting ladders or using MLRS is not allowed until purge",
            "Loot containers will automatically empty themselves within 15 seconds if partially looted. This is to expedite loot spawn",
            "Your auto turrets will never target NPCs e.g Scientists or Scarecrows",
            "The fire torch operates realistically. If you're in a cold biome and light up a torch, it will provide warmth",
            "Everyone has access to the Quick Sort button when interacting with a storage box",
            "You can check the server population with the following command. This information is also displayed at the top left corner",
            "Create a clan. It is the most powerful team system that allows you to create alliances with other clans",
            "All recycles have 2 seconds items recycle time",
            "Open backpacks for extra storage. Everyone have 4 rows. You can get more rows with Elite rank",
            "You can directly upgrade walls, roofs, foundations, etc., while building with Bgrade. Everyone gets access to 1-3",
            "Get exclusive kits with resources and items. Timed ranks get their own exclusive kit",
            "You can save homes as teleport point. There are limitations, 2 Homes, 120 Seconds Cooldown, 20 Seconds Countdown",
            "You can teleport to outpost. Remember we have Merged Bandit Camp in the outpost so just outpost teleportation is available. There are limitations, 120 Seconds Cooldown, 20 Seconds Countdown, 50 Daily TP Limit",
            "Buy your personal vehicles using scrap. These vehicles cannot be stolen by unauthorized players, only by teamates or clanmates. Purchase them once and keep them permanently, even after a wipe. Some vehicles are exclusive to the Elite rank",
            "The server is PVE, so looting boxes for players (unauthorized on TC) is not allowed. However, the owner can make them loot able for other players using these commands",
            "You can pick up your items without damaging them, including walls, quarries, etc. You will also receive a refund",
            "You can trade with players over the distance with the following command",
            "Your crops (farm) are safe from authorized players if they are within TC range. A tip: create a cloth farm, sell cloth for scrap, buy traps with scrap to sell in the server shop for RP",
            "Teleport to players using the following command. There are some limitation, 50 Daily Limit, 20 seconds countdown, 120 Seconds Cooldown",
            "Workbenches have a usage range equal to your TC range. It can be extended by placing TC in your base",
            "You can instantly repair your base with this command. It will toggle base repair, and you will just have to hit the base with a hammer. Resources will be required",
            "All roads are buildable, except the Ring Road and Raid Roads, as they are used for Convoy and Train Heist Events",
            "All types of lanterns will automatically turn on during the night and turn off during daytime. No fuel is required"
        ]
    }
})